[install]
root = "."

[term]
quiet = false
verbose = false
progress.when = 'auto'

[build]
rustc-wrapper = "sccache"
rustflags = [
  #"-Cprefer-dynamic",
  "-Ctarget-cpu=native",
  "-Clinker-plugin-lto",
  "-Clink-arg=-fuse-ld=lld",
  "-Clink-args=-lclang",
  "-Clink-args=-Wl,-rpath,$ORIGIN,-rpath,$ORIGIN/lib,-rpath,$ORIGIN/../lib",
  #"-Cpanic=abort",
  # Set "unwind" if using stdlib
  "-Cpanic=unwind",
  "--verbose",
]

# Use it for stdlib
#rustflags = [
#  #"-Cprefer-dynamic",
#  "-Ctarget-cpu=native",
#  "-Clinker-plugin-lto",
#  "-Clink-arg=-fuse-ld=lld",
#  "-Clink-args=-lclang",
#  "-Clink-args=-Wl,-rpath,$ORIGIN,-rpath,$ORIGIN/lib,-rpath,$ORIGIN/../lib",
#  "-Cpanic=unwind",
#  "--verbose",
#]
